- name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 1. Força a instalação completa das novas dependências do package.json
    - name: Install Node Dependencies
      run: npm install

    # 2. Garante que os Pods nativos (como react-native-svg e expo-file-system) sejam vinculados
    - name: Install CocoaPods
      run: |
        cd ios
        pod install --repo-update
